### ISSUE TITLE
Bot sends low quality photos

### ISSUE THREAD

**Issue by Pranjal-Rajput-IITian** [subinps/Instagram-Bot#1]
**The bot sends compressed images.**
There may be 2 reason :-
1) the images that are downloaded by bot from telegram are in low quality 
2) the bot may be downloading high quality images but are compressed by telegram ( Telegram compresses files only if bot sends 'file as photo.)  This can be overcome by setting 'file as document'.

Hope you understand it and solve this.

**Comment by subinps** [comment]
Will add option to send as photo or document
