### ISSUE TITLE
Account blocked 👀

### ISSUE THREAD

**Issue by Clinton-Abraham** [subinps/Instagram-Bot#7]
![IMG_20210827_010120](https://user-images.githubusercontent.com/70835540/131312831-31567178-2a1e-4bf3-8add-36658c1a9e8e.jpg)

**Comment by subinps** [comment]
I am.not responsible for what youhave done with your account as i have clearly mentioned a disclaimer.
You can recover using that continue button and verifying your identity.
Its because of bulk request by you.
